### ISSUE TITLE
Edgenode only in container 

### ISSUE THREAD

**Issue by rockssk** [loicmathieu/docker-cdh#14]
Hi

  Can I use only the edge node components n services inside the container, while my actual cluster is running remotely on physical machines

Cheers
Suresh

**Comment by loicmathieu** [comment]
Hello,
You can do this but the default hadoop configuration is based on default hostname 'namenode', 'yarnmaster', etc ...
So for this to work you need to override the default hadoop configuration or provide the needed configuration option on the command line.

**Comment by rockssk** [comment]
Thanks, would appreciate if you have a sample
